"""Content generation tools (blogs, SEO articles, emails, social posts, summaries)."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..logging_setup import get_logger
from ..providers.registry import get_registry
from ..providers.base import LLMMessage, LLMRequest, Capability
from ..tools import ToolResult, tool

log = get_logger("cheryy.content")


@tool(
    name="content.blog",
    description="Write a long-form blog / SEO article with intro, sections, conclusion.",
    parameters={
        "type": "object",
        "properties": {
            "topic": {"type": "string"},
            "keywords": {"type": "array", "items": {"type": "string"}},
            "tone": {"type": "string", "default": "professional"},
            "target_words": {"type": "integer", "default": 1200},
            "include_seo": {"type": "boolean", "default": True},
            "save_path": {"type": "string"},
        },
        "required": ["topic", "save_path"],
    },
    category="content",
)
async def content_blog(
    topic: str,
    save_path: str,
    keywords: list[str] | None = None,
    tone: str = "professional",
    target_words: int = 1200,
    include_seo: bool = True,
) -> dict[str, Any]:
    reg = get_registry()
    llm = reg.llm()
    if llm is None:
        return {"error": "no provider"}
    system = (
        "You are CHERYY, an expert copywriter. Produce a structured, factually accurate article. "
        "Do not fabricate quotes, statistics, or people. If you include any references, be conservative."
    )
    kw = ", ".join(keywords or [])
    user = (
        f"Write a {tone} blog article about: {topic}.\n\n"
        f"Target length: ~{target_words} words.\n"
        f"Focus keywords: {kw or '(none)'}.\n"
        + ("Optimise for SEO: include a clear H1, several H2/H3 headings, a meta description (155 chars), and a short URL slug." if include_seo else "")
        + "\n\nReturn JSON with keys: title, slug, meta_description, h1, sections (list of {heading, paragraph}), conclusion."
    )
    req = LLMRequest(
        messages=[LLMMessage(role="user", content=user)],
        system=system,
        response_format_json=True,
        temperature=0.4,
        max_tokens=2048,
    )
    resp = await reg.generate(req, capability=Capability.GENERAL)
    try:
        data = json.loads(resp.content)
    except Exception:
        data = {"title": topic, "h1": topic, "sections": [{"heading": topic, "paragraph": resp.content}], "conclusion": ""}
    # Persist
    Path(save_path).parent.mkdir(parents=True, exist_ok=True)
    md_lines: list[str] = []
    md_lines.append(f"# {data.get('h1') or data.get('title') or topic}")
    md_lines.append("")
    if data.get("meta_description"):
        md_lines.append(f"> Meta: {data['meta_description']}")
        md_lines.append("")
    for s in data.get("sections", []) or []:
        md_lines.append(f"## {s.get('heading','')}")
        md_lines.append(s.get("paragraph", ""))
        md_lines.append("")
    if data.get("conclusion"):
        md_lines.append("## Conclusion")
        md_lines.append(data["conclusion"])
        md_lines.append("")
    md_lines.append(f"_Generated by CHERYY on {datetime.now(timezone.utc).isoformat(timespec='seconds')}Z_")
    Path(save_path).write_text("\n".join(md_lines), encoding="utf-8")
    return {"path": save_path, "title": data.get("title"), "slug": data.get("slug"), "meta_description": data.get("meta_description"), "ok": True}


@tool(
    name="content.seo",
    description="Generate SEO metadata (title, meta, slug, keywords) for a piece of content.",
    parameters={
        "type": "object",
        "properties": {"topic": {"type": "string"}, "body": {"type": "string"}},
        "required": ["topic"],
    },
    category="content",
)
async def content_seo(topic: str, body: str = "") -> dict[str, Any]:
    reg = get_registry()
    llm = reg.llm()
    if llm is None:
        return {"error": "no provider"}
    user = (
        f"Generate SEO metadata for the topic: {topic}.\n"
        "Return JSON with: title (<=60 chars), meta_description (<=155 chars), slug, keywords (list of 5-8), h1.\n"
        f"Body excerpt: {body[:800]}"
    )
    req = LLMRequest(
        messages=[LLMMessage(role="user", content=user)],
        response_format_json=True,
        max_tokens=512,
    )
    resp = await reg.generate(req, capability=Capability.GENERAL)
    try:
        data = json.loads(resp.content)
    except Exception:
        data = {"title": topic, "meta_description": "", "slug": topic.lower().replace(" ", "-"), "keywords": [], "h1": topic}
    return data


@tool(
    name="content.write",
    description="General-purpose short-form writing (email, post, caption, proposal).",
    parameters={
        "type": "object",
        "properties": {"format": {"type": "string"}, "topic": {"type": "string"}, "tone": {"type": "string", "default": "professional"}, "length": {"type": "string", "default": "short"}},
        "required": ["format", "topic"],
    },
    category="content",
)
async def content_write(format: str, topic: str, tone: str = "professional", length: str = "short") -> dict[str, Any]:
    reg = get_registry()
    llm = reg.llm()
    if llm is None:
        return {"error": "no provider"}
    user = (
        f"Write a {length} {format} about: {topic}.\n"
        f"Tone: {tone}. Don't fabricate facts. Return only the written content, no preamble."
    )
    req = LLMRequest(messages=[LLMMessage(role="user", content=user)], max_tokens=1024)
    resp = await reg.generate(req, capability=Capability.GENERAL)
    return {"content": resp.content}


@tool(
    name="content.summarize",
    description="Summarise a long text into a concise, useful summary.",
    parameters={
        "type": "object",
        "properties": {"text": {"type": "string"}, "max_words": {"type": "integer", "default": 200}, "style": {"type": "string", "default": "concise"}},
        "required": ["text"],
    },
    category="content",
)
async def content_summarize(text: str, max_words: int = 200, style: str = "concise") -> dict[str, Any]:
    reg = get_registry()
    llm = reg.llm()
    if llm is None:
        return {"error": "no provider"}
    user = f"Summarise the following text in <= {max_words} words, {style} style:\n\n{text[:60000]}"
    req = LLMRequest(messages=[LLMMessage(role="user", content=user)], max_tokens=512)
    resp = await reg.generate(req, capability=Capability.GENERAL)
    return {"summary": resp.content}